import css from "@/styles/shared/ImageHolder.module.css";
import LoadingBubbles from "./LoadingBubbles";
import { useState } from "react";
import Image from "next/image";
import { IconButton } from "@mui/material";

interface ImageHolderProps {
  src: string;
  width: number;
  height: number;
  alt?: string;
  hasTools?: boolean;
}

export default function ImageHolder({
  width,
  height,
  hasTools = false,
  src: imageUrl,
  alt: imageName = "Image generated by Cellesseon",
}: ImageHolderProps) {
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isDownloading, setIsDownloading] = useState<boolean>(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const response = await fetch(
        `/api/download?url=${encodeURIComponent(imageUrl)}`
      );
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = imageName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Download failed:", error);
    }
    setIsDownloading(false);
  };

  return (
    <div className={css.wrapper}>
      {isLoading ? (
        <span className="flex p-4">
          <LoadingBubbles size="small" />
        </span>
      ) : (
        hasTools && (
          <IconButton
            loading={isDownloading}
            onClick={handleDownload}
            size="small"
            sx={{
              padding: "4px 7px",
              borderRadius: "8px!important",
              lineHeight: 1,
              zIndex: 10,
              position: "absolute",
              bottom: "0.5rem",
              right: "0.5rem",
              backgroundColor: "rgba(0, 0, 0, 0.5)",
            }}
          >
            <i className="bi bi-download"></i>
          </IconButton>
        )
      )}

      <Image
        priority
        src={imageUrl}
        width={width}
        height={height}
        loading="eager"
        onLoad={() => setIsLoading(false)}
        alt={imageName}
        className={`${isLoading ? "hidden" : css.showImg}`}
        sizes={`(max-width: 768px) 100vw, (max-width: 1200px) 50vw, ${width}px`}
      />
    </div>
  );
}
