import css from "@/styles/shared/ImageHolder.module.css";
import LoadingBubbles from "./LoadingBubbles";
import { useState } from "react";
import Image from "next/image";

interface ImageHolderProps {
  src: string;
  width: number;
  height: number;
  alt?: string;
}

export default function ImageHolder({
  src,
  width,
  height,
  alt,
}: ImageHolderProps) {
  const [isLoading, setIsLoading] = useState<boolean>(true);

  return (
    <div className={css.wrapper}>
      {isLoading && (
        <span className="flex p-4">
          <LoadingBubbles size="small" />
        </span>
      )}
      <Image
        priority
        src={src}
        width={width}
        height={height}
        loading="eager"
        onLoad={() => setIsLoading(false)}
        alt={alt || "Image generated by Cellesseon"}
        className={`${isLoading ? "hidden" : css.showImg}`}
        sizes={`(max-width: 768px) 100vw, (max-width: 1200px) 50vw, ${width}px`}
      />
    </div>
  );
}
